name: wallet
description: A clean finance tracker.
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2  # <--- Manually add this line here
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true